---
- name: Dependency
  hosts: localhost
  tasks:
  - name: "Create docker network(s)"
    docker_network:
      name: "{{ item.name }}"
      state: present
      ipam_config:
        - subnet: "{{ item.subnet }}"
      labels:
        owner: molecule
    with_items:
      - name: lan
        subnet: 10.0.1.0/24
      - name: wan
        subnet: 10.0.2.0/24
    delegate_to: localhost
